export const FRESHUSERID = 'FRESHUSERID';
export const FRESHRECOMMEND = 'FRESHRECOMMEND';
export const SENDSHADOW = 'SENDSHADOW';
export const FRESHWALLS = 'FRESHWALLS';
export const FRESHSORT = 'FRESHSORT';
export const CHANGEOWN = 'CHANGEOWN';
export const FRESHPERSONAL = 'FRESHPERSONAL';
